TDD_App/routes/web.php
<?php


use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');});
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::name('products.')->prefix('products')
    ->group(function(){
        Route::get('/',[ProductController::class,'index'])->name('index');
        Route::post('/',[ProductController::class,'store'])->name('store')
            ->middleware('auth');
        Route::get('/create',[ProductController::class,'create'])->name('create');
        Route::get('/{id}',[ProductController::class,'show'])->name('show');
        Route::delete('/{id}',[ProductController::class,'destroy'])->name('delete')
            ->middleware('auth');
        Route::get('/{id}/edit',[ProductController::class,'edit'])->name('edit')
            ->middleware('auth');
        Route::put('/{id}',[ProductController::class,'update'])->name('update')
            ->middleware('auth');
    });

Route::name('users.')->prefix('users')
    ->group(function(){
        Route::get('/',[UserController::class,'index'])->name('index');
        Route::post('/',[ProductController::class,'store'])->name('store')
            ->middleware('auth');
//        Route::get('/create',[ProductController::class,'create'])->name('create');
        Route::get('/{id}',[UserController::class,'show'])->name('show');
//        Route::delete('/{id}',[ProductController::class,'destroy'])->name('delete')
//            ->middleware('auth');
//        Route::get('/{id}/edit',[ProductController::class,'edit'])->name('edit')
//            ->middleware('auth');
//        Route::put('/{id}',[ProductController::class,'update'])->name('update')
//            ->middleware('auth');
    });

TDD_App/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

TDD_App/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;


use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class UserController extends Controller
{
    protected $user;

    /**
     * @param $user
     */
    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = $this->user->latest('id')->paginate(5);
        return view('users.index',compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = $this->user->create($request->all());
        return response()->json([],Response::HTTP_CREATED);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user= $this->user->findOrFail($id);
        return view('users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

TDD_App/resources/views/users/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
{{--        <form class="form-inline" action="{{route('products.index')}}" method="GET">--}}
{{--            @csrf--}}
{{--            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="key" value="{{request(('key'))}}">--}}
{{--            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>--}}
{{--        </form>--}}

        <h1>User Manager</h1>
        <a href=""  class="btn btn-success" style="margin-bottom: 10px">Create User</a>
        <div class="row justify-content-center">

            <table class="table table-striped">
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>content</th>
                    <th>role</th>
                    <th>option</th>
                </tr>
                @foreach($user as $user)
                    @csrf
                    <tr>
                        <th>{{$user->id}}</th>
                        <th>{{$user->name}}</th>
                        <th>{{$user->email}}</th>
                        <th>1</th>
                        <th>
                            <a class="btn btn-success" href="{{route('users.show',$user->id)}}">view</a>
{{--                        @auth()--}}
{{--                            <form action="{{route('products.delete',$product->id)}}" method="POST">--}}
{{--                                @method('DELETE')--}}
{{--                                @csrf--}}
{{--                                <button class="btn btn-danger">delete</button>--}}
{{--                            </form>--}}
{{--                            <a class="btn btn-primary" href="{{route('products.edit',$product->id)}}">edit</a>--}}
{{--                        @endauth--}}

                            <button class="btn btn-primary">edit</button>
                            <button class="btn btn-danger">delete</button>
                        </th>
                    </tr>
                @endforeach
            </table>

        </div>
{{--        {{$user->links() }}--}}
    </div>
@endsection

TDD_App/resources/views/users/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <h1>User Manager</h1>
        <div class="row justify-content-center">
            <a class="btn btn-outline-primary" href="{{route('users.index')}}" style="margin-bottom: 10px">Back List User</a>
            <table class="table table-striped">
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>mail</th>
                    <th>password</th>
                    <th>role</th>
                    <th>option</th>
                </tr>
                    @csrf
                    <tr>
                        <th>{{$user->id}}</th>
                        <th>{{$user->name}}</th>
                        <th>{{$user->email}}</th>
                        <th>{{$user->password}}</th>
                        <th>1</th>
                        <th>
                            {{--                            <a class="btn btn-success" href="{{route('products.show',$product->id)}}">view</a>--}}
                            {{--                        @auth()--}}
                            {{--                            <form action="{{route('products.delete',$product->id)}}" method="POST">--}}
                            {{--                                @method('DELETE')--}}
                            {{--                                @csrf--}}
                            {{--                                <button class="btn btn-danger">delete</button>--}}
                            {{--                            </form>--}}
                            {{--                            <a class="btn btn-primary" href="{{route('products.edit',$product->id)}}">edit</a>--}}
                            {{--                        @endauth--}}

                            <button class="btn btn-primary">edit</button>
                            <button class="btn btn-danger">delete</button>
                        </th>
                    </tr>
            </table>
        </div>
    </div>
@endsection