TDD_App/routes/web.php
<?php


use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');});
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::name('products.')->prefix('products')
    ->group(function(){
        Route::get('/',[ProductController::class,'index'])->name('index');
        Route::post('/',[ProductController::class,'store'])->name('store')
            ->middleware('auth');
        Route::get('/create',[ProductController::class,'create'])->name('create');
        Route::get('/{id}',[ProductController::class,'show'])->name('show');
        Route::delete('/{id}',[ProductController::class,'destroy'])->name('delete')
            ->middleware('auth');
        Route::get('/{id}/edit',[ProductController::class,'edit'])->name('edit')
            ->middleware('auth');
        Route::put('/{id}',[ProductController::class,'update'])->name('update')
            ->middleware('auth');
    });

Route::name('users.')->prefix('users')
    ->group(function(){
        Route::get('/',[UserController::class,'index'])->name('index');
        Route::post('/',[ProductController::class,'store'])->name('store')
            ->middleware('auth');
//        Route::get('/create',[ProductController::class,'create'])->name('create');
        Route::get('/{id}',[UserController::class,'show'])->name('show');
//        Route::delete('/{id}',[ProductController::class,'destroy'])->name('delete')
//            ->middleware('auth');
//        Route::get('/{id}/edit',[ProductController::class,'edit'])->name('edit')
//            ->middleware('auth');
//        Route::put('/{id}',[ProductController::class,'update'])->name('update')
//            ->middleware('auth');
    });

TDD_App/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table='products';
    protected $fillable=['name','content'];

    public function search(string $key){
        return $this->where('name','like','%'.$key.'%')->latest('id')->paginate(5);
    }
}

TDD_App/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProductRequest;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    protected $product;

    public function __construct(Product $product)
    {
        $this->product = $product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
//        $products = Product::all();
//        return view('products.index',compact('products'));
        $key = $request->input('key') ?? '';
        $products = $this->product->search($key);
        return view('products.index',compact('products'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $this->product->create($request->all());
        return redirect()->route('products.index');
    }

    /**
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = $this->product->findOrFail($id);
        return view('products.show',compact('product'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = $this->product->findOrFail($id);
        return view('products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = $this->product->findOrFail($id);
        $product->update($request->all());
        return redirect()->route('products.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = $this->product->findOrFail($id);
        $product->delete();
        return redirect()->route('products.index');
    }

}

TDD_App/resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Product Insert</h2> <br/>
                <form action="{{route('products.store')}}" method="POST">
                    @csrf
                    <div class="card-header">
                        <input type="text" class="form-group" name="name" placeholder="insert name">
                        @error('name')
                        <span class="error text-danger" id="name-error" for="name">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="card-body">
                        <input type="text" class="form-group" name="content" placeholder="insert content">
                    </div>
                    <button class="btn btn-success">bam thu ma xem</button>
                </form>
            </div>
        </div>
    </div>
@endsection

TDD_App/resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Product Insert</h2> <br/>
                <form action="{{route('products.update',$product->id)}}" method="POST">
{{--                    --}}
                    @method('PUT')
                    @csrf
                    <div class="card-header">
                        <input type="text" class="form-group" name="name" value="{{$product->name}}">
                        @error('name')
                        <span class="error text-danger" id="name-error" for="name">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="card-body">
                        <input type="text" class="form-group" name="content" value="{{$product->content}}">
                    </div>
                    <button class="btn btn-success">bam thu ma xem</button>
                </form>
            </div>
        </div>
    </div>
@endsection

TDD_App/resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <form class="form-inline" action="{{route('products.index')}}" method="GET">
            @csrf
            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="key" value="{{request(('key'))}}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <a href="{{route('products.create')}}"  class="btn btn-success">Create Products</a>

        <div class="row justify-content-center">
            <table class="table table-striped">
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>content</th>
                    <th>option</th>
                </tr>
                @foreach($products as $product)
                    @csrf
                    <tr>
                        <th>{{$product->id}}</th>
                        <th>{{$product->name}}</th>
                        <th>{{$product->content}}</th>
                        <th>
                            <a class="btn btn-success" href="{{route('products.show',$product->id)}}">view</a>
{{--                            @auth()--}}
                            <form action="{{route('products.delete',$product->id)}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger">delete</button>
                            </form>
                            <a class="btn btn-primary" href="{{route('products.edit',$product->id)}}">edit</a>
{{--                            @endauth--}}
                        </th>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection

TDD_App/resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @csrf
            <table class="table table-striped">

                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>content</th>
                    <th>option</th>
                </tr>
                    <tr>
                        <th>{{$product->id}}</th>
                        <th>{{$product->name}}</th>
                        <th>{{$product->content}}</th>
                        <th>
                            <form action="{{route('products.delete',$product->id)}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger">delete</button>
                            </form>
                            <a class="btn btn-primary" href="{{route('products.edit',$product->id)}}">edit</a>
                        </th>
                    </tr>
            </table>
        </div>
    </div>
@endsection